### ISSUE TITLE
#[serde(flatten)] does not seem to work when serializing

### ISSUE THREAD

**Issue by 0x6273** [BurntSushi/rust-csv#155]
#### What version of the `csv` crate are you using?

```
csv = { git = "https://github.com/BurntSushi/rust-csv" }
serde = { version = "1.0", features = ["derive"] }
```

#### Briefly describe the question, bug or feature request.

Flattening a struct using the #[serde(flatten)] field attribute works as expected when deserializing, but not when serializing.

#### Include a complete program demonstrating a problem.

```rust
use serde::{Serialize, Deserialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct StructA {
	foo: String,
	#[serde(flatten)]
	struct_b: StructB,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct StructB {
	bar: String,
	baz: String,
}

fn main() {
	let test = StructA {
		foo: "asdf".to_string(),
		struct_b: StructB {
			bar: "asdf".to_string(),
			baz: "asdf".to_string(),
		},
	};

	let json = r#"{"foo":"asdf","bar":"asdf","baz":"asdf"}"#;
	let csv_ = "foo,bar,baz\nasdf,asdf,asdf\n";

	// json serialization works as expected
	assert_eq!(serde_json::to_string(&test).unwrap(), json);

	// so does deserialization
	let test2: StructA = serde_json::from_str(json).unwrap();
	assert_eq!(test, test2);

	// csv deserialization works
	let test3: StructA = csv::Reader::from_reader(csv_.as_bytes())
		.deserialize().next().unwrap().unwrap();
	assert_eq!(test, test3);

	// csv serialization results in an error:
	// Error(Serialize("serializing maps is not supported, ..."))
	let mut output: Vec<u8> = Vec::new();
	{
		let mut writer = csv::Writer::from_writer(&mut output);
		let result = writer.serialize(test);
		assert!(result.is_ok()); // fails
	}
	assert_eq!(std::str::from_utf8(&output).unwrap(), csv_);
}
```

#### What is the observed behavior of the code above?

```
RUST_BACKTRACE=1 cargo +nightly run
   Compiling csv_flatten_test v0.1.0 (/home/ben/Projects/rust/csv_flatten_test)
    Finished dev [unoptimized + debuginfo] target(s) in 1.12s
     Running `target/debug/csv_flatten_test`
thread 'main' panicked at 'assertion failed: result.is_ok()', src/main.rs:46:3
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/00859e3e653973120006aaf3227823062dde1ba7/src/libstd/panicking.rs:408
   6: csv_flatten_test::main
             at src/main.rs:46
   7: std::rt::lang_start::{{closure}}
             at /rustc/00859e3e653973120006aaf3227823062dde1ba7/src/libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  10: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  11: std::rt::lang_start
             at /rustc/00859e3e653973120006aaf3227823062dde1ba7/src/libstd/rt.rs:64
  12: main
  13: __libc_start_main
  14: _start
```

#### What is the expected or desired behavior of the code above?

See asserts in the code above.

**Comment by BurntSushi** [comment]
The assert isn't particularly helpful. Could you please show the error message?

Frankly, I've found `serde(flatten)` to be very inconsistent with how it works. If it works, it's great, but it doesn't always behave as one expects because there are many caveats to its usage.

While I haven't looked into your specific issue (I'd like to see an error message first), please consider searching this issue tracker for `serde(flatten)` issues. There have been a few of them and they probably contain useful context.

**Comment by 0x6273** [comment]
Here is the error message I'm getting: https://github.com/BurntSushi/rust-csv/blob/366c07528af626318c1cc8c172e3242b7fe12570/src/serializer.rs#L198-L201

I searched the issue tracker and found a [patch](https://github.com/Kampfkarren/rust-csv/commit/95cea44329d97179ba998a2c30285eeda9c84ac2) that fixes this issue.

**Comment by BurntSushi** [comment]
Okay... So the error message is just saying that it isn't supported. Please consider documenting your use case here: https://github.com/BurntSushi/rust-csv/issues/98
