### ISSUE TITLE
Serializing arrays with headers returns error

### ISSUE THREAD

**Issue by Geemili** [BurntSushi/rust-csv#68]
This is using serde on the `rewrite` branch.

Creating struct with an array in it causes `csv::Writer::serialize` to return an `UnequalLengths` error. Disabling headers prevents the error from occuring.

```rust
#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate csv;

#[derive(Serialize)]
struct Foo {
    datas: [String; 2],
}

fn main() {
    let mut writer = csv::WriterBuilder::new().from_path("test.csv").unwrap();
    let data = Foo {
        datas: ["Hello".into(), "world".into()],
    };
    writer.serialize(data).unwrap();
}
```

```
 $ env RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/rust-csv-example`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnequalLengths { pos: None, expected_len: 1, len: 2 }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: rust_csv_example::main
             at ./src/main.rs:17
  12: std::panicking::try::do_call
             at /checkout/src/libstd/panicking.rs:454
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by BurntSushi** [comment]
What do you expect the behavior to be? i.e., Can you show me the CSV data you expect to have?

**Comment by Geemili** [comment]
```
datas0,datas1
Hello,world
```

However, I can see this as something that others wouldn't expect. Maybe repeat the name?

```
datas,datas
Hello,world
```

It would be great if the error message could be made clearer. The current error message doesn't point to the real source of the problem, but I haven't worked with the code enough to know if this is plausible to implement.

**Comment by BurntSushi** [comment]
I'm not sure how to make this better. Choosing arbitrary header names seems bad and so does repeating header names. In fact, even if we wanted to do it, I don't think we could. CSV fundamentally does not support arbitrarily nested types. All you get is a sequence of records. The automatic serialization basically flattens any nested sequences, which is why you're seeing the error you got.

I think one possible way to improve the error message is to completely ban nested sequences when headers are being written. I think that's OK, since it seems like they are incompatible behaviors.

**Comment by BurntSushi** [comment]
OK, the `rewrite` branch should now have the error handling I described in my previous comment.

**Comment by BurntSushi** [comment]
There are also some docs/examples on the `Writer::serialize` method.
